beechit/fal_securedownload

Classes/Hooks/AbstractBeButtons.php, Classes/Hooks/DocHeaderButtonsHook.php, Classes/Service/UserFileMountService.php, ext_tables.php
=> [BUGFIX] Restore PHP 5.3 compatibility

Classes/Configuration/ExtensionConfiguration.php, Classes/FormEngine/DownloadStatistics.php, Classes/Hooks/FileDumpHook.php, Configuration/TCA/Overrides/fe_users.php, Documentation/Misc/Index.rst, Resources/Private/Language/locallang_be.xlf, ext_conf_template.txt, ext_localconf.php, ext_tables.sql
=> [FEATURE] Track file downloads and show statistics in fe_user record

Classes/Security/CheckPermissions.php, Classes/ViewHelpers/Security/AssetAccessViewHelper.php
=> [BUGFIX] Ensure feGroups is a string before using it

Resources/Private/Partials/FileTree/Leaf.html
for not convertable subFolder object #65
=> Remove ' in template

Classes/FormEngine/DownloadStatistics.php, Configuration/TCA/Overrides/fe_users.php, Resources/Private/Language/locallang_be.xlf
- better performance of SQL query
- properly group on the file name to avoid empty results
- show info text if there are no downloads yet
- add a TCA label for the download field
=> [TASK] Improve download statistics

Classes/Domain/Repository/ProcessedFileRepository.php, Classes/FormEngine/DownloadStatistics.php, Classes/Hooks/FileDumpHook.php, Classes/Security/CheckPermissions.php, Classes/Service/Utility.php
By using the Doctrine DBAL API in TYPO3 v8.7 and above the extension now
works when using PostgreSQL too.
=> [FEATURE] Support for PostgreSQL in TYPO3 v8.7

Configuration/TCA/Overrides/sys_file_metadata.php, Configuration/TCA/tx_falsecuredownload_folder.php
Should fix https://github.com/beechit/fal_securedownload/issues/115
=> [FEATURE] Add search to fe_group TCA entry #115

Classes/Hooks/FileDumpHook.php
Pull request to resolve #124
Thanks
=> [FEATURE] Allow to use typolink for the redirects URL

Classes/ViewHelpers/DownloadLinkViewHelper.php
=> [FEATURE] initialize parent arguments

Documentation/Settings.cfg
Added the new settings.cfg file to uphold the new documentation: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html#migrate
=> [MERGE] Added Settings.cfg

Classes/Controller/FileTreeController.php
=> [FIX] Error if settings.storage is empty

composer.json
https://github.com/beechit/fal_securedownload/issues/159
https://gitlab.beech.it/CMS/project-planning/-/issues/1057
=> [MERGE] add extension key to composer.json

Classes/Hooks/FileDumpHook.php
https://github.com/beechit/fal_securedownload/issues/150
=> [TASK] Fix problem with t3://page... links

Configuration/TypoScript/setup.txt, Resources/Private/Layouts/Default.html, Resources/Public/JavaScript/CollapsibleFolderTree.js
With this the Javascript is only included where needed.
Resolves: #155
=> [TASK] Include Javascript only where needed

Classes/EventListener/FolderChangedEventListener.php
=> [BUGFIX] Fix cut/paste folders

Classes/Controller/FileTreeStateController.php, Classes/FormEngine/DownloadStatistics.php, Classes/Hooks/AbstractBeButtons.php, Classes/Service/LeafStateService.php, Configuration/Services.yaml, Configuration/TCA/Overrides/tt_content.php
This solves an exception when saving the LeafState. Deleted the old entry for corresponding removed class.
=> [BUGFIX] Add FileTreeStateController to Services.yaml 

Classes/Hooks/KeSearchFilesHook.php
=> [BUGFIX] Fix ke_search indexing

Configuration/TCA/tx_falsecuredownload_download.php, Configuration/TCA/tx_falsecuredownload_folder.php, Resources/Private/Language/locallang_db.xlf
=> [BUGFIX] Add TCA for downloads

Classes/EventListener/ModifyFileDumpEventListener.php
=> [BUGFIX] Fix TypeError exception in ModifyFileDumpEventListener

Classes/Security/CheckPermissions.php
=> [BUGFIX] Fix permission check for non-admin backend users

Configuration/TCA/tx_falsecuredownload_download.php
=> [BUGFIX] Fix reference to fe_users in downloads table
